version: '1.0'

services:
  opensearch:
    image: opensearchproject/opensearch:3.1.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
      bootstrap.memory_lock: 'true'
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: gKL-TVxTv3e
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"   # TCP input
      - "5045:5045"   # HTTP input
      - "9601:9600"   # Logstash monitoring API (HTTP)
    networks:
      - opensearch-net
    depends_on:
      - opensearch

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: http://admin:admin@opensearch:9200
    ports:
      - 5601:5601
    networks:
      - opensearch-net
    depends_on:
      - opensearch

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge
